import Head from 'next/head';
import UserBar from '../components/userBar/UserBar';
import { useState } from 'react';
import { authStateListener } from './api/firebase-config';

import styles from '../styles/Home.module.css';

export default function Home() {
  const [user, setUser] = useState();
  authStateListener(setUser);


  return (
    <div className={styles.container}>
      <Head>
        <title>Next Fullstack App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.appContainer}>
        <UserBar user={user} />

      </div>
    </div>
  );
}
