import Head from 'next/head';
import UserBar from '../components/userBar/UserBar';
import MessageBox from '../components/messageBox/MessageBox';
import { useState } from 'react';
import { signInUser, authStateListener } from './api/firebase-config';

import styles from '../styles/Home.module.scss';

export default function Home() {
  const [user, setUser] = useState();
  authStateListener(setUser);


  return (
    <div className={styles.container}>
      <Head>
        <title>Next Fullstack App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Pacifico&display=swap" rel="stylesheet" />
      </Head>

      <div className={styles.appContainer}>
        <div className={styles.contentContainer}>
          {user ?
            <>
              <UserBar user={user} />
              <p className={styles.subtitle}>Hellur</p>
              < MessageBox />
            </>
            : null
          }
          {!user ?
            <>
              <p className={styles.title}>Hellur</p>
              <p className={styles.title}>How yer dern?</p>
              <button className={styles.signIn} onClick={signInUser}>Sign In</button>
            </>
            : null}
        </div>
      </div>

    </div>
  );
}
